export enum SING_IN_TYPE {
    SIGN_IN_SUCCESS = 'SIGN_IN:SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE = 'SIGN_IN:SIGN_IN_FAILURE',
    SIGN_IN_START = 'SIGN_IN:SIGN_IN_START',
    SIGN_IN_LOADING = 'SIGN_IN:SIGN_IN_LOADING',
    CHECK_USER_SESSION = 'SIGN_IN:CHECK_USER_SESSION',
}
