export enum AUTH_TYPE {
    SIGN_IN_SUCCESS = 'AUTH:SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE = 'AUTH:SIGN_IN_FAILURE',
    SIGN_IN_START = 'AUTH:SIGN_IN_START',
    CHECK_USER_SESSION = 'AUTH:CHECK_USER_SESSION',
}
